using UnityEngine;
using UnityEngine.InputSystem; // Necesario para el nuevo sistema de entrada

public class MenuPausa : MonoBehaviour
{
    [Header("Referencias UI")]
    public GameObject panelPausa;       // El objeto visual (Canvas/Panel) que tiene los botones
    public InputActionAsset inputAsset; // El archivo de configuraci칩n de controles (.inputactions)

    // Variables internas
    private InputAction pauseAction; // La "tecla" espec칤fica que vamos a escuchar
    private bool estaPausado = false; // Estado del juego (쮺orriendo o Quieto?)

    void Awake()
    {
        // 1. B칔SQUEDA DE LA ACCI칍N
        // No hardcodeamos teclas (no ponemos "Escape"). 
        // Buscamos la acci칩n abstracta "Pause" dentro del mapa "Player".
        // As칤 funcionar치 igual si pulsas ESC en teclado o START en un mando.
        var actionMap = inputAsset.FindActionMap("Player");
        pauseAction = actionMap.FindAction("Pause");
    }

    // OnEnable y OnDisable son OBLIGATORIOS para gestionar eventos de Input System
    void OnEnable()
    {
        pauseAction.Enable(); // Encendemos la escucha
        
        // SUSCRIPCI칍N AL EVENTO:
        // "Cuando se realice (performed) la acci칩n de Pausa, ejecuta la funci칩n AlternarPausa".
        // Esto es mucho m치s eficiente que preguntar en el Update todo el rato.
        pauseAction.performed += Context => AlternarPausa();
    }

    void OnDisable()
    {
        pauseAction.Disable(); // Apagamos la escucha al salir
    }

    // --- L칍GICA DE DETENCI칍N DEL TIEMPO ---

    public void AlternarPausa()
    {
        estaPausado = !estaPausado; // Invertimos el valor (True <-> False)

        if (estaPausado)
        {
            // EL TRUCO DEL TIEMPO:
            // Poner timeScale a 0 congela todo lo que use Time.deltaTime.
            // (Animaciones, F칤sicas, Movimiento de enemigos...).
            Time.timeScale = 0f; 
            
            panelPausa.SetActive(true); // Mostramos el men칰 visual
        }
        else
        {
            Reanudar();
        }
    }

    public void Reanudar()
    {
        estaPausado = false;
        
        // Volvemos a la normalidad (1 = velocidad normal)
        Time.timeScale = 1f; 
        
        panelPausa.SetActive(false); // Ocultamos el men칰
    }

    public void Salir()
    {
        Debug.Log("游녦 Saliendo del juego...");
        Application.Quit(); // Cierra la ventana del juego (solo en la Build final)
    }
}